// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxjhrcbaHqADpHKKcuqAzIHF3WtAZE_XY',
    appId: '1:26779214736:web:42edaac77fc89afecec915',
    messagingSenderId: '26779214736',
    projectId: 'panel-surya-iot',
    authDomain: 'panel-surya-iot.firebaseapp.com',
    storageBucket: 'panel-surya-iot.firebasestorage.app',
    measurementId: 'G-2R2GLRD988',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI8M8SFH8RzGIDIKZGpEBmaWyYFwiquyI',
    appId: '1:26779214736:android:d77b7e3e559a842bcec915',
    messagingSenderId: '26779214736',
    projectId: 'panel-surya-iot',
    storageBucket: 'panel-surya-iot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxpaFkJFFYwzpA295sIAZKbi2Ixm7BKLM',
    appId: '1:26779214736:ios:c292468901478639cec915',
    messagingSenderId: '26779214736',
    projectId: 'panel-surya-iot',
    storageBucket: 'panel-surya-iot.firebasestorage.app',
    iosBundleId: 'com.example.panelSurya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxpaFkJFFYwzpA295sIAZKbi2Ixm7BKLM',
    appId: '1:26779214736:ios:c292468901478639cec915',
    messagingSenderId: '26779214736',
    projectId: 'panel-surya-iot',
    storageBucket: 'panel-surya-iot.firebasestorage.app',
    iosBundleId: 'com.example.panelSurya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxjhrcbaHqADpHKKcuqAzIHF3WtAZE_XY',
    appId: '1:26779214736:web:b2f1c27277b6322acec915',
    messagingSenderId: '26779214736',
    projectId: 'panel-surya-iot',
    authDomain: 'panel-surya-iot.firebaseapp.com',
    storageBucket: 'panel-surya-iot.firebasestorage.app',
    measurementId: 'G-LH66NCRCB3',
  );
}
